version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: always
    environment:
      CASSANDRA_CLUSTER_NAME: "netQuestCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_PASSWORD_SEEDER: "true"
      CASSANDRA_USER: "netQuest"
      CASSANDRA_PASSWORD: "netQuestLocal"
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data: